import {useState, useMemo} from 'react';
import {Table, Checkbox} from 'antd';
import {traverse} from '@/utils/highlight';
import {createRegExp} from '@/utils/object.ts';
import './index.less';

// 中医院

// 科室1
const ke1 = [
  {
    doctorId: '2018426',
    docHisId: '1553',
    docName: '陈光宇',
    level: ' ',
    beGoodAt:
      '高血压病、高心病、冠心病、心肌炎、心肌病、心力衰竭、心律失常、高脂血症、心血管神经症、失眠、头痛等疾病的治疗。',
    description:
      '<p> <b>四川省名中医，</b><b>主任医师，</b><b>四川省中医药学会心脑血管病专委会委员</b><b>，</b><b>四川省中西医结合学会心血管病专委会委员，四川省中医药介入心脏病学</b><b>会</b><b>专委会委员，本硕连读七年制硕士研究生导师。1984年</b><b>毕业于成都中医药大学</b><b>(</b><b>原成都中医学院）医学系，学士学位，</b><b>毕业后长期在本院从事临床医疗、教学和科研工作。先后发表论文十多篇，负责及参加部省级和厅局级科研课题多项。</b><b>从医</b><b>30</b><b>多年来，</b><b>对中医胸痹心痛，</b><b>风眩，</b><b>心瘅，心痹，心衰，心悸，不寐，头痛等疾病的辨证施治有丰富的临床经验和独到之处。</b> </p> <p> <b></b> </p>',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/7/d/0/c/5ed5c36bd5c54.jpg',
    createTs: '2023-03-03 06:26:16',
    updataTs: '2024-05-01 19:50:24',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '84729531',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1553&deptHisId=45||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2019212',
    docHisId: '1575',
    docName: '高培阳',
    level: ' ',
    beGoodAt:
      '冠心病、动脉斑块、心力衰竭、高血压、心律失常、心肌病、肺心病、痛风等疾病的中医及中西医结合治疗，尤其擅长各类疑难杂症的诊断及处理。',
    description:
      '医学博士，博士生导师，天府名医，四川省名中医，四川省有突出贡献的专家，四川省中医管理局学术技术带头人，四川省卫健委领军人才。中国中西结合协会重症专业委员会副主任委员，世界中医药联合会急诊专业委员会副会长，四川省中医药学会重症专业委员会主任委员，四川省医师协会重症专业委员会副会长，四川省医学会重症专业委员会常务委员。四川省中医重症质量控制中心主任，四川省医学会医疗事故技术鉴定专家，成都市医疗保险局第三方评审专家。',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/0/d/3/9/5ed4b5ac308af.jpg',
    createTs: '2023-03-08 06:23:21',
    updataTs: '2024-05-01 19:52:18',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '45306669',
    doc_code: null,
    tooltips: '',
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1575&deptHisId=45||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018428',
    docHisId: '1560',
    docName: '贾秀兰',
    level: ' ',
    beGoodAt: '冠心病、高血压、心力衰竭、心肌病、心肌炎、心律失常的中西医结合治疗。',
    description:
      '毕业于成都中医药大学，精于中西医理论和实践。从事心血管疾病的中西医诊治30余年。擅长冠心病、高血压病、心肌病、心肌炎、心力衰竭、心律失常、心脏神经症等疾病的诊治，并有独到的见解和治法。对中老年疾病的预防保健有较深的研究。',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/6/5/d/c/5ed704497c823.jpg',
    createTs: '2023-03-03 06:26:16',
    updataTs: '2024-05-01 19:54:23',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '94464815',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1560&deptHisId=45||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2025094',
    docHisId: '2856',
    docName: '王国道',
    level: ' ',
    beGoodAt:
      '心脑血管疾病：高血压病、冠心病、心律失常、心力衰竭、失眠、脑血管疾病后遗症、衰老及老年痴呆防治等内科常见疾病。  ',
    description:
      '<p>\r\n\t中医内科主任医师，第四批四川省名中医，四川省首届健康卫士。从事内科临床及医院业务管理工作40年。近10年来潜心探索糖尿病和高血压的中西医结合治疗和预防，曾与国内著名的糖尿病专家仝小林院士、林兰教授、庞国明教授和心脑血管病专家张伯礼院士多次学术交流。用中西结合方法诊疗内儿科常见病、多发病及疑难杂症，特别对糖尿病、高血压、高脂血症、肺结节等心、肺、脑血管及代谢性疾病的中西医结合预防、治疗有丰富的临床经验和独到见解。撰写学术论文30余篇，完成省、市科研项目四项，主编出版医学专著三部（《大黄的临床应用与研究》《人参的临床应用与研究》《名老中医学术思想汇编》）。\r\n</p>',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/9/2/8/f/653f708d0cde6.jpg',
    createTs: '2023-10-04 06:25:23',
    updataTs: '2024-05-01 19:54:23',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '58316323',
    doc_code: null,
    tooltips: '',
    profession_img: null,
    political_face: '',
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=2856&deptHisId=45||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2026206',
    docHisId: '2885',
    docName: '燕纯伯',
    level: ' ',
    beGoodAt: '心血管疑难危急重症，特别是对高血压，冠心病，心衰，心律失常，瓣膜病有独到之处。',
    description:
      '1982年四川医学院硕士研究生毕业，博士研究生导师，国家二级教授；国务院特殊政府津贴；四川省学术和技术带头人。卫生部全国优选50名医师之一，由卫生部外事司长带队，赴日本，受时任总理大臣竹下登首相接见并合影，人民日报有报道，是对中国医师的最高礼仪。由日中医学会指派，到日本最大的医院藤田医科大学附属医院研修急救和介入心脏病学；并指派时任全日本心脏病学会主席水野康教授作指导教官，他也是该医院的心内科主任。参加卫生部组织的归国专家义诊团，到西藏多地义诊。美国总统卡特访问成都期间，由政府指定作为贴身随同保健医师。曾任：四川省医师协会副会长，四川省医学会常务理事，四川省心血管病专委会副主任委员，《心血管病学进展》杂志主编。曾在华西医院，成都市第三人民医院，四川省人民医院和成都大学附属医院工作过。有丰富的临床经验并掌握国内外最新诊断治疗动态和进展。',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/0/6/7/2/6571165850a74.jpg',
    createTs: '2023-11-25 06:25:22',
    updataTs: '2024-05-01 19:54:23',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '26670458',
    doc_code: null,
    tooltips: '',
    profession_img: null,
    political_face: '',
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=2885&deptHisId=45||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018429',
    docHisId: '1572',
    docName: '姚萍',
    level: ' ',
    beGoodAt: '高血压，冠心病，高脂血症，心力衰竭，心肌炎，心律失常，心神经官能症，头晕头痛，失眠等疾病的诊治。',
    description: '',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/0/3/e/4/5ed5c462f0968.jpg',
    createTs: '2023-03-03 06:26:16',
    updataTs: '2024-05-01 19:54:23',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '39474711',
    doc_code: null,
    tooltips: '',
    profession_img: null,
    political_face: '',
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1572&deptHisId=45||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018431',
    docHisId: '1563',
    docName: '张泉',
    level: ' ',
    beGoodAt:
      '运用中西医结合的新理念、新技术治疗心血管科各类疾病，尤擅长于对冠心病、各类急慢性心力衰竭、复杂心律失常、心肌炎、心肌病、高脂血症、高血压病、脑动脉硬化症、失眠等疾病的治疗。',
    description:
      '成都中医药大学教授，主任医师，硕士研究生导师，四川省名中医。毕业于华西医科大学，已从事中西医结合的临床、教学、科研工作近40年。 现任四川省中医学会心衰专委会副主委，中国老年医学学会高血压分会四川省级工作组组员，中国高血压联盟-云贵川联盟理事，中国医药教育协会中西医结合心血管专业委员会委员，成都医养结合促进会高血压分会常委，成都市医养结合促进会理事，四川省中西医结合心脏介入专委会委员等，共公开发表学术论文50余篇，主持和主研课题8项，主编或参编教材14部，为全国中医药行业高等教育“十三五”“十四五”规划教材《内科学》副主编，精品课程《内科学》课程负责人。',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/7/2/2/b/5ed708f058b5d.jpg',
    createTs: '2023-03-03 06:26:16',
    updataTs: '2024-05-01 19:53:18',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '32082341',
    doc_code: null,
    tooltips: '',
    profession_img: null,
    political_face: '',
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1563&deptHisId=45||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018655',
    docHisId: '1554',
    docName: '何芳',
    level: ' ',
    beGoodAt:
      '高血压病，冠心病，高脂血症，心力衰竭，心律失常，头晕、头痛、胸闷、胸痛、心悸、气短、失眠等多种心脑血管系统疾病。',
    description:
      '毕业于重庆医科大学，从医二十多年来，一直在临床一线工作，曾在解放军总医院、第二军医大学深入进修学习。发表论文十余篇，获军队科技进步三等奖，对心脑血管系统疾病等的防治有较深入的研究和丰富的临床经验。',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/2/7/0/2/617f4668a35e5.jpg',
    createTs: '2023-03-04 06:28:18',
    updataTs: '2024-05-01 19:54:23',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '98519881',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1554&deptHisId=45||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2019092',
    docHisId: '1576',
    docName: '张松',
    level: ' ',
    beGoodAt:
      '2022年支援拉萨抗疫，中医治疗患者，效果良好。急慢性心力衰竭、高血压、冠心病（心绞痛、心肌梗死）、心律失常、心肌病、心脏瓣膜病，以及失眠、多梦、急慢性咳嗽、鼻炎、鼻窦炎等内科杂病。致力于中西医结合治疗高血压病，纯中药治疗部分早期高血压具有较好疗效。',
    description:
      '<p style= "text-indent:14.0000pt; "> 成都中医药大学中西医结合临床博士，取得中国超声协作组心脏高级培训班认证、中国医药教育协会首届国际肺部超声导师资格、美国心脏学会（AHA）高级生命支持资格认证。 </p> <p> 现任中国中医药研究促进会疑难杂症分会常务理事、中国中医药研究促进会免疫病分会常务理事、中国康复医学会高压氧专业委员会委员、世界中医药联合协会热病专业委员会会员、成都市医学会重症医学分会青年委员。目前主持省部级课题1项，厅局级课题5项，以第一作者/通讯作者发表SCI及中文核心论文20余篇。 </p>',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/c/5/c/5/604884fc625b5.jpg',
    createTs: '2023-03-07 06:26:27',
    updataTs: '2024-05-01 19:54:23',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '68135649',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1576&deptHisId=45||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018430',
    docHisId: '1574',
    docName: '邹元',
    level: ' ',
    beGoodAt:
      '冠心病、高血压、心律失常、心肌炎、心肌病、心力衰竭、心悸、心慌、胸闷、胸痛、胸部不适、心烦、神差乏力、头昏、头晕、头痛、失眠、下肢水肿、心神经管能证、心血管疾病风险评估与康复治疗等.',
    description: '四川省中医药学会介入心脏病学专委会常委、四川省中医药学会络病专业委员会委员。',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/1/5/d/f/5ed70935c13c5.jpg',
    createTs: '2023-03-03 06:26:16',
    updataTs: '2024-05-01 19:54:23',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '40156451',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1574&deptHisId=45||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2019093',
    docHisId: '1556',
    docName: '黄大军',
    level: ' ',
    beGoodAt:
      '冠心病，心力衰竭，各种心律失常，高血压病，心肌病，高脂血症，心血管神经官能症，心血管介入诊治技术，心脑血管病康复治疗。',
    description:
      '医学硕士，擅长采用中西医结合的办法治疗各类心血管疾病，包括冠心病、急慢性心衰、各类复杂心律失常、高血压病、风心病、心肌病、心肌炎等多种心血管疾病。从事心血管介入工作多年，包括冠脉造影术，冠脉内支架植入术，起搏器植入术，射频消融术，左心耳封堵术，卵圆孔封堵术等。在国内各类心血管核心杂志发表学术论文数篇。',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/3/9/8/1/6282f53b3a8a8.jpg',
    createTs: '2023-03-07 06:26:27',
    updataTs: '2024-05-01 19:54:23',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '80994121',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1556&deptHisId=45||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2027980',
    docHisId: '1557',
    docName: '孔令秋',
    level: ' ',
    beGoodAt:
      '疑难、复杂、高危冠心病介入治疗，在顽固性心力衰竭、恶性心律失常、难治性高血压、心脏瓣膜病、心包积液、卵圆孔未闭、房间隔缺损、左心耳封堵方面，积累了丰富经验。',
    description:
      '医学博士，先后就读于四川大学华西临床医学院、复旦大学上海医学院，师从我国著名心脏病学家唐红教授、葛均波院士。承担国家及省部级科研项目3项，在国内外医学期刊发表文章60余篇，主编/译医学专著7部，参编10余部。现为《中华高血压杂志》、《中华心血管病杂志》等期刊审稿人，主要社会兼职包括中国CTO老伙计俱乐部成员，中国冠状动脉慢性闭塞病变介入治疗俱乐部成员，中国超声心动图学会专家会员、海峡两岸医药卫生交流协会心血管专委会委员，中国医药教育协会麻醉超声专委会副主委、四川省中西医结合学会心血管专委会常委，四川省中医药学会介入心脏病学分会委员、四川省医师协会高血压医师分会青年委员。',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '',
    createTs: '2024-01-19 12:45:25',
    updataTs: '2024-05-01 19:54:23',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '36118317',
    doc_code: null,
    tooltips: '',
    profession_img: null,
    political_face: '',
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1557&deptHisId=45||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2019091',
    docHisId: '1558',
    docName: '李燕伟',
    level: ' ',
    beGoodAt:
      '采用中西医结合的新理念、新技术诊治冠心病、急慢性心衰、各类复杂心律失常、高血压病、老年性心脏病、风心病、心肌病、心肌炎等心血管疾病，对于以上疾病治疗擅长采用中医中药进行调理与康复，尤其头晕、高血压、冠心病、心力衰竭等中医治疗方面有显著疗效。',
    description:
      '毕业于成都中医药大学，2017年-2018年于华西心内科及介入导管室学习，擅长采用中西医结合的办法治疗各类心血管疾病，主研参与国家及省部级科研课题4项，以第一作者在国内各类心血管核心杂志发表学术论文10余篇。',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/d/e/c/8/61236127ab5c8.jpg',
    createTs: '2023-03-07 06:26:27',
    updataTs: '2023-09-28 16:59:16',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '82399653',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1558&deptHisId=45||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2025573',
    docHisId: '1555',
    docName: '唐翰章',
    level: ' ',
    beGoodAt:
      '从事心血管介入诊疗多年，熟练掌握各类心血管介入诊疗技术；擅长中西医结合诊治各类心血管疾病，对冠心病、急慢性心力衰竭、各类复杂心律失常、高血压病、风心病、心肌病、心肌炎、结构性心脏病有独到见解。',
    description:
      '主治医师，心血管专业硕士研究生，毕业于成都中医药大学，现任双流区中医院心内科学科主任。从事心血管介入工作多年，累计完成各类心血管介入手术3000余例，其中冠脉支架植入术500余例，单腔、双腔、三腔、ICD心脏永久起搏器300余例，心电生理检查术、二维、三维各类射频消融术300余例，熟练掌握冠脉内旋磨术、卵圆孔封堵术、冠脉内FFR测定、IVUS检查、冠脉内OCT检查术等前沿技术。在国内各类心血管核心杂志发表学术论文数篇。目前为中国医药教育协会胸痛专委会委员、四川省中医药信息学会慢病专委会委员、四川省社区卫生协会全科专委会委员，成都市医师协会心血管病专委会委员。',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/6/3/8/e/656540bcf045d.jpg',
    createTs: '2023-10-24 06:24:22',
    updataTs: '2024-05-01 19:54:23',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '40610134',
    doc_code: null,
    tooltips: '',
    profession_img: null,
    political_face: '',
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1555&deptHisId=45||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018925',
    docHisId: '1573',
    docName: '殷拥军',
    level: ' ',
    beGoodAt:
      '冠心病、心力衰竭，心律失常，高血压病、高脂血症、心脏瓣膜病、心肌炎、心脏神经官能症等心血管疾病的中西医结合治疗及中医药调理。率先在国内开展CCM植入术，率先在院内开展CRTD、左心耳封堵、无导线起搏器植入等心血管前沿诊疗技术。',
    description:
      '心血管一科主任，高血压达标中心主任，金牛区技能精英，成都中医药大学重点学科负责人，中国医师协会心力衰竭专家委员会委员，四川省医学会起搏电生理专委会委员。',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/1/e/4/d/5e81b69789bc6.jpg',
    createTs: '2023-03-06 06:23:21',
    updataTs: '2024-05-01 19:54:23',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '50321504',
    doc_code: null,
    tooltips: '',
    profession_img: null,
    political_face: '',
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1573&deptHisId=45||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018427',
    docHisId: '1559',
    docName: '伍洲',
    level: ' ',
    beGoodAt:
      '冠心病，心力衰竭，各种心律失常，高血压病，心肌病，高脂血症，肺源性心脏病，心血管神经官能症，心血管介入诊治技术，心脑血管病康复治疗。',
    description:
      '成都中医药大学心血管专业硕士研究生。擅长采用中西医结合的办法治疗各类心血管疾病，包括冠心病、急慢性心衰、各类复杂心律失常、高血压病、风心病、心肌病、心肌炎等多种心血管疾病。从事心血管介入工作多年，累计完成各类心血管介入手术3000余例，包括冠脉造影术，支架植入术，各类起搏器植入术，射频消融术、左心耳封堵术等；致力于心律失常的“绿色电生理”手术，让更多心律失常患者接受手术时免于X射线的危害；熟练运用床旁彩超检测诊断各种心血管疾病。在国内各类心血管核心杂志发表学术论文数篇。目前为四川省中医药学会介入心脏病学专委会秘书；中国中药协会心血管药物研究专委会委员。四川省医促协会高血压分会委员。',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/9/2/c/a/6109e3bc21032.jpg',
    createTs: '2023-03-03 06:26:16',
    updataTs: '2024-05-01 19:50:24',
    districtId: '63',
    deptHisId: '45||ZK',
    profession: '医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '79659755',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1559&deptHisId=45||ZK&districtCode=2&regType=3',
  },
];

// 科室2
const ke2 = [
  {
    doctorId: '2018926',
    docHisId: '1539',
    docName: '刘永家',
    level: ' ',
    beGoodAt: '心、脑血管硬化，冠心病、胸痹，高血压病、眩晕，心律失常、心悸，咳嗽，气管、支气管炎等。',
    description:
      '四川省名中医，四川省有突出贡献的专家，全国中西医结合学会＂优秀中青年科技工作者＂、四川省康复医学会副主任委员、四川省中医药学会理事、成都市心血管专委会委员。从事临床医学35余年，对高血压病、冠心病、心律失常、心力衰竭、肺心病、高脂血症等心血管疾病以及慢性支气管炎、贫血、血栓塞性疾病有独特的认识并擅长用中医或中西医结合的方法治疗该类疾病。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/5/c/f/a/5ed70e17c92d0.jpg',
    createTs: '2023-03-06 06:23:22',
    updataTs: '2024-05-01 19:49:24',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '35528191',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1539&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018656',
    docHisId: '1541',
    docName: '王卫星',
    level: ' ',
    beGoodAt:
      '心力衰竭、冠心病、心肌缺血、高血压病、心律失常、瓣膜性心脏病、心肌病、心脏神经症、心血管介入技术；头痛、眩晕、胸闷、胸痛、心悸、气短、中风、失眠、多梦、等多种心脑血管疾病。',
    description:
      '1982年毕业于成都中医药大学（原成都中医学院）医疗系。现任成都中医药大学附属医院心血管二科负责人，大内科副主任，主任医师，硕士生导师，四川省名中医，目前担任中国医师协会中西医结合分会高血压专家委员会委员、环球中医药杂志编委、四川省中医药学会中医内科老年病专委会委员、四川省中医药学会心脑血管病专委会委员、四川省中西医结合学会心血管病专委会委员、成都市医学会心血管专委会委员、成都市医学会循证医学专委会委员。从事临床及教学30余年。主持国家级科研课题3项；省级科研课题4项；厅级课题2项。参加国家级及省部级课题4项。在国内医学专业杂志发表论文40余篇。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/5/d/5/6/5ed70e563c18f.jpg',
    createTs: '2023-03-04 06:28:18',
    updataTs: '2024-05-01 19:50:23',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '19694495',
    doc_code: null,
    tooltips: '',
    profession_img: null,
    political_face: '',
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1541&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018437',
    docHisId: '1552',
    docName: '谢文',
    level: ' ',
    beGoodAt:
      '运用中西医结合方法诊断治疗高血压、冠心病、急慢性心衰、各种复杂的心律失常、心肌炎、心肌病、先天性心脏病、心脏瓣膜病、心血管疑难疾病等，有深厚的医学理论、丰富和独到的临床经验，擅长心血管疾病冠脉介入、射频消融术、起搏器植入术、TAVR等。在预防心脏疾病、双心医学、心脏康复、中医适宜技术方面有深厚的',
    description:
      '教授、主任医师、硕士研究生导师，四川省名中医，四川省中医心血管专业质控中心业务主任，四川省中医药管理局学术和技术带头人，成都中医药大学附属医院心血管学科带头人，成都中医药大学附属医院胸痛中心、心衰中心业务总监，成都中医药大学附属医院心血管二科科主任，国家中医心血管病临床研究中心四川省中医院分中心主任，奥地利开普勒大学心脏中心访问学者，四川省中医系统心血管专科联盟牵头人，四川省中医药学会心衰(心力衰竭)专委会主任委员，四川省重大疾病心衰病中医药防治中心负责人，四川省中西医结合学会心血管专委会副主任委员，中国中医药学会基层高血压专家指导委员会专家，四川省心脑血管病防治专项行动专家组副组长，四川省老龄健康发展中心中医组副组长',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/8/a/0/2/62a28b148efca.jpg',
    createTs: '2023-03-03 06:26:16',
    updataTs: '2024-05-01 19:50:23',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '63138898',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1552&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2030074',
    docHisId: '1542',
    docName: '杨思进',
    level: ' ',
    beGoodAt: null,
    description: null,
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: null,
    createTs: '2024-04-25 10:17:28',
    updataTs: '2024-04-28 16:56:16',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '65726214',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1542&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018438',
    docHisId: '1533',
    docName: '高林林',
    level: ' ',
    beGoodAt:
      '冠心病、高血压病、心肌炎、心律失常、心力衰竭、肺心病、风心病、高脂血症等，以及其他常见疾病如咳嗽、慢性胃病、绝经前后综合征等。',
    description:
      '2001年硕士毕业参加工作，2009年博士毕业于成都中医药大学中西医结合专业。从事中西医结合临床心血管工作近20年，积累了较丰富的临床经验，尤擅长对常见高发的心血管疾病如冠心病（心绞痛及心梗、支架植入术后）、高血压病、心律失常、心脏瓣膜病、肺心病、心肌病、慢性心衰、心脏神经症等病的诊治，对于本专业的疑难杂症处理也有一定的心得和独到见解。多年来跟随名师坐诊，潜心钻研传统中医对心病的认识，熟练运用经方验方治疗胸痹风眩等中医证候，疗效确切。担任国家级十二五规划教材《诊断学基础》编委，精编教材《诊断学》编委。任四川省中西医结合学会会员，成都市医学会会员，四川省康复医学会肺康复专委会委员。曾获得成都中医药大学及附属医院优秀共产党员称号。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/c/1/4/d/5ed7135fcfb9d.jpg',
    createTs: '2023-03-03 06:26:16',
    updataTs: '2023-06-20 16:57:20',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '29620991',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1533&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018432',
    docHisId: '1534',
    docName: '韩震',
    level: ' ',
    beGoodAt:
      '运用中医及中西医结合方法治疗内科疾病，尤其擅长心血管疾病的治疗，如高血压、冠心病、心肌炎、心律失常、心力衰竭、肺心病、风心病、高脂血症等，以及其他常见疾病如咳嗽、慢性胃病、绝经前后综合征等。师从著名中医内科学专家李明富教授，重视脏腑理论、气血津液学说，尤其擅长运用活血化瘀法、益气活血法、行气活血法、',
    description:
      '1985年本科毕业于成都中医学院医学系,留院工作，先后在急重症研究室、心血管内科从事中西医结合临床、教学、科研工作。曾在四川大学华西医院进修一年。承担科研项目10余项，参与的四川省科技厅课题益气通脉口服液治疗冠心病的新药研究与开发获2005年度成都市科技进步二等奖。公开发表论文10余篇；参加编写学术论著2部。临床带教研究生、本科生、进修生、外国留学生；指导硕士研究生一名；承担本科生西医诊断学课程讲授工作。中医学会会员，中华医学会会员，中西医结合学会会员。曾任四川省中西医结合心血管专委会委员、秘书。<!--EndFragment-->',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/a/e/5/e/5ed709a25bb35.jpg',
    createTs: '2023-03-03 06:26:16',
    updataTs: '2024-05-01 19:50:25',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '34587896',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1534&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018436',
    docHisId: '1550',
    docName: '胡蓉',
    level: ' ',
    beGoodAt:
      '对高血压病、高血压心脏病、急慢性心力衰竭、冠心病、不稳定型心绞痛、心肌梗死，冠脉支架植入术后心绞痛、微血管型心绞痛、心律失常（房颤、早搏）、瓣膜性心脏病（风湿性心脏病）、心肌炎、心肌病、心脏神经症，胃心综合征、胆心综合征等心血管疾病的诊治及共病管理，对中医病症如心悸、胸痹心痛、头痛、中风、水肿、失眠',
    description:
      '2005年毕业于成都中医药大学中西医结合临床专业，获硕士学位。师从原中医附院大内科主任戴万亨教授、四川省人民医院心血管内科专家姜荣建主任医师。从事中西医结合临床、教学、科研10余年，参与多项国家级、厅局级、院级课题，在国家级核心期刊发表论文数篇，参编专著2部。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/b/9/6/d/5ed5c4bf6384c.jpg',
    createTs: '2023-03-03 06:26:16',
    updataTs: '2024-05-01 19:50:25',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '60865447',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1550&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018439',
    docHisId: '1536',
    docName: '黄睿臻',
    level: ' ',
    beGoodAt: '慢性心力衰竭、高血压病、冠心病、心律失常等心血管疾病的中西医结合治疗。',
    description:
      '毕业于成都中医药大学中西结合专业，从事中西医结合临床工作多年，师从四川省名中医刘永家主任医师，四川省第五届师承学员，擅长中西医结合治疗慢性心力衰竭、高血压病等心血管疾病，目前主持厅局级课题4项，其他各级课题4项，主研国家级课题2项，获得专利4项，公开发表文章10余篇。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/1/7/a/4/5ed75b92c3f61.jpg',
    createTs: '2023-03-03 06:26:16',
    updataTs: '2024-04-27 11:28:21',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '93655559',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1536&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018930',
    docHisId: '1551',
    docName: '姜莉',
    level: ' ',
    beGoodAt:
      '通过辩证论治治疗风眩、胸痹、心悸、失眠、盗汗、水肿等病症，擅长病种：高血压病、冠心病、心律失常、瓣膜性心脏病、心肌病、慢性心衰、心脏神经症、盗汗、水肿。掌握心血管微创介入手术（冠脉造影术、冠脉内支架植入术、射频消融术、心脏起搏器植入术）的理论知识和操作。',
    description:
      '副主任医师，毕业于重庆医科大学临床医学系。2003年在成都中医药大学附属医院从事临床心血管内科工作至今，并承担心血管科研究生、本科生教学工作。具有较强的临床工作能力，较全面、系统的了解及掌握心血管专业的西医及中医基础理论和专业知识，熟练掌握心血管科临床技术理论和相关前沿理论知识，参与多项国家级、厅局级、校级、院级课题，在国家核心期刊发表论文数十篇，sci两篇，主编专著2部。现任中国心脏联盟心血管疾病预防与康复专业委员会四川联盟常委、四川省中医药学会心衰专委会常委、成都医学会心血管专科分会青年委员会委员、四川省老年医学会介入专委会委员、金牛区“首席家庭医生”。2015年被四川省卫生计生委选派参加援非洲安哥拉医疗队，在安哥拉共和国执行为期两年半的援助任务。<br />',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/7/f/a/1/60b9eada19cb7.jpg',
    createTs: '2023-03-06 06:23:22',
    updataTs: '2024-04-25 11:29:24',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '16765854',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1551&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018434',
    docHisId: '1540',
    docName: '王琳',
    level: ' ',
    beGoodAt:
      '治疗高血压、冠心病、心律失常，心衰、心脏神经症、老年病，胃心综合症，眩晕、头痛、胸痛、失眠、心悸、郁症、胃痞、胃痛，水肿，虚劳等。运用中西医理论，结合舌脉辩证处方。',
    description:
      '1985年毕业于成都中医药大学医学系，学士学位。临床工作近40年，长期从事心血管临床、科研、教学工作，经验丰富。目前担任四川省中医药学会心衰专委会常委，擅长运用中医八钢辩证并结合西医现代诊疗技术诊病处方。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/c/6/d/5/65541a36a8f00.jpg',
    createTs: '2023-03-03 06:26:16',
    updataTs: '2024-05-01 19:50:23',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '47604661',
    doc_code: null,
    tooltips: '',
    profession_img: null,
    political_face: '',
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1540&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2019342',
    docHisId: '1545',
    docName: '张德来',
    level: ' ',
    beGoodAt:
      '心力衰竭、冠心病、心肌缺血、高血压病、心律失常、瓣膜性心脏病、心肌病、心脏神经症、心血管介入技术；头痛、眩晕、胸闷、胸痛、心悸、气短、中风、失眠、多梦、等多种心脑血管疾病。',
    description:
      '副主任医师,中西医结合硕士研究生，中医世家。毕业于成都中医药大学，师从四川省名中医刘永家教授。从事中西医结合临床、科研、教学工作十余年，有丰富的内科知识、中西医结合心血管及心血管介入技术的临床经验，对冠心病、心力衰竭尤为关注，发表医学论文数十篇，参与多项国家级、省部级、院校级课题。现任世界中联中药上市后再评价专业委员会第二届理事会理事，成都市医学会心血管分会委员，老年医学会胸痹（冠心病）专委会委员，老年医学会介入专委会委员。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/b/b/b/1/5ed70ee26b551.jpg',
    createTs: '2023-03-09 06:22:23',
    updataTs: '2024-04-25 11:29:24',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '25865283',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1545&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018657',
    docHisId: '1549',
    docName: '钟丹',
    level: ' ',
    beGoodAt:
      '运用中医及中西医结合的方法治疗内科杂病，尤其擅长胸痹、心痛、头痛、眩晕、心慌心悸、高血压、高脂血症、老年性心脏病、高血压病等；对亚健康疲劳、焦虑、失眠、汗证、耳鸣、咳嗽等亦有独到的见解；临床医学博士，潜心临床10余年，在药物治疗之外，更予以食疗内调、外治等中医古方治疗。',
    description:
      '女，临床医学博士；2008年毕业于成都中医药大学。全省第五批老中医药专家学术经验继承人；全国中医药研究促进会中医全科与养生分会委员；全科医学专委会第一届委员；四川省中医药信息学会委员。潜心临床10余年，擅长应用中西医结合的方法治疗胸痹、心痛、头痛、眩晕、心慌心悸、高血压、高脂血症、老年性心脏病等；对亚健康疲劳、焦虑、失眠、汗证、耳鸣、咳嗽等亦有独到的见解。在临床诊疗中，倡导除药物治疗以外的生活、情绪、心理、饮食、运动等多种治疗方式，针对不同的疾病、不同的体质给予完善的健康生活指导。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/c/7/f/3/5ed705db6cda9.jpg',
    createTs: '2023-03-04 06:28:18',
    updataTs: '2024-05-01 19:50:25',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '35450040',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1549&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2019094',
    docHisId: '1543',
    docName: '刘蕾',
    level: ' ',
    beGoodAt:
      '冠心病，高血压病 高血压心脏病，风湿性心脏病，急慢性心力衰竭，心律失常等多种心血管疾病的中西医结合诊治。以及心脏神经功能紊乱引起的各种症状的治疗。',
    description:
      '毕业于成都中医药大学中西结合硕士专业，从事中西医结合临床工作多年，师从四川省十大名中医刘永家教授，擅长通过中医辨证论治改善胸痛、心衰、心律失常、高血压、冠心病等心血管疾病症状及预后，擅长中西医结合治疗心悸、头痛、眩晕等症。心衰中心委员，老年病协会委员，参与研究国家自然科学基金课题，多项国家级、厅局级、校级课题，发表包括SCI 核心期刊等多篇论文。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/9/d/4/5/6109e44f97cd9.jpg',
    createTs: '2023-03-07 06:26:27',
    updataTs: '2024-05-01 19:50:25',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '57324004',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1543&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018927',
    docHisId: '1544',
    docName: '聂谦',
    level: ' ',
    beGoodAt: '胸痛、失眠、头痛、眩晕、心力衰竭、心律失常、冠心病、高血压病、高脂血症，心血管介入诊疗技术。',
    description:
      '毕业于成都中医药大学，医学世家，九三社员，承担心血管科规培医生、研究生、本科生教学工作；从事临床工作多年，擅长通过辨证论治治疗胸痛、心悸、失眠、头痛等病症，擅长运用中医内治法治疗高血压、高脂血症、高血糖，擅长用水针疗法治疗心脾病症，协助开发院内制剂益心通痹合剂治疗冠心病；同时从事心血管介入诊疗工作，擅长冠心病的急诊介入，擅长各种类型起搏器的植入（CRT-D,CRT,ICD等），累计完成各类心血管介入手术数千例（包括急性心肌梗死介入诊疗，复杂冠脉病变介入诊疗等）；参与多项国家级、厅局级、校级课题，发表论文数十篇，现任四川省中医药学会心衰专委会副秘书长、委员，中医大九三学社青年委员，四川省老年医学会胸痹（冠心病）专委会委员，四川省老年医学会介入专委会委员。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/5/9/f/3/5e8eba185f505.jpg',
    createTs: '2023-03-06 06:23:22',
    updataTs: '2024-05-01 19:50:25',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '81676755',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1544&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2021783',
    docHisId: '1720',
    docName: '唐秀容',
    level: ' ',
    beGoodAt:
      '中西医结合治疗高血压病、冠心病、高脂血症、心律失常、心肌缺血、心脏神经官能症等各种心血管疾病及失眠、眩晕、郁证、咳嗽等内科疾病。',
    description:
      '毕业于成都中医药大学中西医结合硕士心血管内科专业，中医世家，师从四川省名中医刘永家教授，从事中西医结合临床、教学、科研工作15余年，现任：中国医学生物技术协会心电学技术分会动态心电图专业委员会委员，中国老年学和老年医学学会老年病学分会委员，\r\nCMIA心脏监护专业委员会/CPDE心脏监护技术专业委员会第六届委员会专家委员，，四川省中医药学会心力衰竭专委会第一届委员会委员，四川省医师协会心电学医师分委员兼秘书，参与多项国家级、厅局级、校级课题，发表包括SCI核心期刊多篇论文。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/7/1/2/4/64672352551c0.jpg',
    createTs: '2023-05-18 06:25:23',
    updataTs: '2024-05-01 19:47:18',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: null,
    doc_code: null,
    tooltips: '',
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1720&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018928',
    docHisId: '1535',
    docName: '王岚',
    level: ' ',
    beGoodAt: '中西医结合治疗慢性心衰、心律失常、高血压病、冠心病、高脂血症、胸痹、心悸、眩晕等心血管常见疾病。',
    description:
      '毕业于成都中医药大学，硕士研究生，四川省中医药学会心力衰竭专业委员会委员。师从四川省名中医刘永家主任医师，从事中西医结合防治心血管疾病专业。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/0/c/b/3/5ed70ea201a21.jpg',
    createTs: '2023-03-06 06:23:22',
    updataTs: '2024-05-01 19:50:25',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '13711673',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1535&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018433',
    docHisId: '1537',
    docName: '向劲松',
    level: ' ',
    beGoodAt:
      '以脉辨证、循脉诊病。擅长中西医结合治疗眩晕、胸闷、便秘、心悸、失眠、情志不舒、胸痹心痛（冠心病）、中风（脑出血/脑梗塞）、心衰病（心力衰竭）、心悸病（心律失常）、风眩病（高血压病）、心瘅（心肌炎）、心胀病（各类心肌病）等心系、肝系、脾系疾病，重点开展中医精准医学心系及神经系统疾病研究。',
    description:
      '成都中医药大学中西医结合博士，师从四川省学术技术带头人钟森教授和四川省名中医刘永家教授，有脉诊专长，能通过中医传统辨证与现代医学结合进行综合诊治。从事临床工作多年，对中医精准医学体系下的心系、肝系、脾胃、肾脏及神经系统疾病诊治具有独到见解。 中医脉诊，是通过丰富的脉象信息，对全身各系统状态进行综合判断，对疾病的病机病理进行精准分析，并给予近期和中长期诊疗计划的过程。因脉由心起、血随肝藏，五脏气血阴阳及邪气盛衰皆可由脉精确判断，故脉诊对中医辨证辨病均有极高价值。 中医精准医学是在中医精准辨证辨病的基础上，结合现代医学对疾病的进一步精确定位、定性与定量诊疗，能提供完整的优化诊疗，起到事半功倍、调病求机的效果。 现任四川省医学会科普分会青年委员、四川省中医药学会急诊专委会青年委员、四川省中医药学卫生经济专委会秘书长，参与多项国家级、厅局级、校级课题，并担任本科生导师和研究生临床带教工作。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/f/2/e/8/5ed5c55fc64ae.jpg',
    createTs: '2023-03-03 06:26:16',
    updataTs: '2024-04-28 16:56:16',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '12352449',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1537&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018435',
    docHisId: '1546',
    docName: '张宏才',
    level: ' ',
    beGoodAt: '冠心病，高血压病，心力衰竭，各类心律失常。',
    description:
      '民盟盟员，主治医师，毕业于成都中医药大学附属医院，获硕士学位，从事心血管临床工作多年，擅长心血管疾病的介入治疗，独立行冠脉造影2000余台，各类支架植入术500余台，起搏器500余台，射频消融600余台，包括阵发性室上速，室性早搏，室速等，对高血压病有独到的见解，对心力衰竭采用中西结合治疗有较好的临床疗效。在国内核心期刊发表文章10余篇。四川省医学会高级会员。四川省老年医学会冠心病胸痹专委会委员。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/a/0/b/f/5ed5c66ec5861.jpg',
    createTs: '2023-03-03 06:26:16',
    updataTs: '2024-05-01 19:50:23',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '16577730',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1546&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2019213',
    docHisId: '1713',
    docName: '张雪梅',
    level: ' ',
    beGoodAt: '高血压、冠心病、心绞痛、急慢性心力衰竭、慢性阻塞性肺疾病、消化道出血、中风、重大疾病之后的康复等。',
    description:
      '<p> 硕士，主治医师，毕业于成都中医药大学附属医院中西医结合临床专业重症医学方向。通过中华医学会重症医学专科资质认证，取得中国重症超声组心脏高级培训证书。收治危重症医学科各种类型的休克、心衰、呼吸衰竭、急性肾衰竭、各种大手术后支持治疗、创伤、消化道出血、重症胰腺炎等，熟练掌握诊治危重病各种临床操作技能。主持和参加多项国家级、省部级课题，发表SCI 3篇，中文核心期刊2篇。<b></b> </p>',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/e/1/b/c/61430e7dc9b5b.jpg',
    createTs: '2023-03-08 06:23:21',
    updataTs: '2024-03-04 16:56:22',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '86938547',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1713&deptHisId=46||ZK&districtCode=2&regType=3',
  },
  {
    doctorId: '2018929',
    docHisId: '1547',
    docName: '赵珏',
    level: ' ',
    beGoodAt: '冠心病，心力衰竭，心律失常，高血压病，失眠、头痛、眩晕，心血管介入诊治技术。',
    description:
      '医师，硕士研究生，毕业于成都中医药大学。从事临床工作多年。擅长中医辨证治疗胸痛、心悸、失眠、头痛、眩晕等病症，同时从事心血管介入诊疗工作，包括冠心病介入以及起搏器植入手术等介入心脏病学诊疗技术，累计完成各类心血管介入手术数千例（包括急性心肌梗死介入诊疗，复杂冠脉病变介入诊疗，防猝死起搏器植入技术等）；参与多项国家级、厅局级、校级课题。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/6/b/8/1/5ed5c6e32313d.jpg',
    createTs: '2023-03-06 06:23:22',
    updataTs: '2024-05-01 19:50:23',
    districtId: '63',
    deptHisId: '46||ZK',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '66828294',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1547&deptHisId=46||ZK&districtCode=2&regType=3',
  },
];

// 房颤
const list3 = [
  {
    doctorId: '2019383',
    docHisId: '1563',
    docName: '张泉',
    level: ' ',
    beGoodAt:
      '运用中西医结合的新理念、新技术治疗心血管科各类疾病，尤擅长于对冠心病、各类急慢性心力衰竭、复杂心律失常、心肌炎、心肌病、高脂血症、高血压病、脑动脉硬化症、失眠等疾病的治疗。',
    description:
      '成都中医药大学教授，主任医师，硕士研究生导师，四川省名中医。毕业于华西医科大学，已从事中西医结合的临床、教学、科研工作近40年。 现任四川省中医学会心衰专委会副主委，中国老年医学学会高血压分会四川省级工作组组员，中国高血压联盟-云贵川联盟理事，中国医药教育协会中西医结合心血管专业委员会委员，成都医养结合促进会高血压分会常委，成都市医养结合促进会理事，四川省中西医结合心脏介入专委会委员等，共公开发表学术论文50余篇，主持和主研课题8项，主编或参编教材14部，为全国中医药行业高等教育“十三五”“十四五”规划教材《内科学》副主编，精品课程《内科学》课程负责人。',
    deptName: '房颤门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/9/1/6/c/607ea217eb8b4.jpg',
    createTs: '2023-03-09 06:23:04',
    updataTs: '2024-04-25 11:59:20',
    districtId: '63',
    deptHisId: '1f5c12b84c59df6f6a16626336eea79a||ZB',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '32082341',
    doc_code: null,
    tooltips: '',
    profession_img: null,
    political_face: '',
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1563&deptHisId=1f5c12b84c59df6f6a16626336eea79a||ZB&districtCode=2&regType=3',
  },
  {
    doctorId: '2019139',
    docHisId: '1556',
    docName: '黄大军',
    level: ' ',
    beGoodAt:
      '冠心病，心力衰竭，各种心律失常，高血压病，心肌病，高脂血症，心血管神经官能症，心血管介入诊治技术，心脑血管病康复治疗。',
    description:
      '医学硕士，擅长采用中西医结合的办法治疗各类心血管疾病，包括冠心病、急慢性心衰、各类复杂心律失常、高血压病、风心病、心肌病、心肌炎等多种心血管疾病。从事心血管介入工作多年，包括冠脉造影术，冠脉内支架植入术，起搏器植入术，射频消融术，左心耳封堵术，卵圆孔封堵术等。在国内各类心血管核心杂志发表学术论文数篇。',
    deptName: '房颤门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/a/7/a/9/6282f55e8e8c4.jpg',
    createTs: '2023-03-07 06:27:07',
    updataTs: '2024-05-01 19:55:21',
    districtId: '63',
    deptHisId: '1f5c12b84c59df6f6a16626336eea79a||ZB',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '80994121',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1556&deptHisId=1f5c12b84c59df6f6a16626336eea79a||ZB&districtCode=2&regType=3',
  },
  {
    doctorId: '2019254',
    docHisId: '1559',
    docName: '伍洲',
    level: ' ',
    beGoodAt:
      '冠心病，心力衰竭，各种心律失常，高血压病，心肌病，高脂血症，肺源性心脏病，心血管神经官能症，心血管介入诊治技术，心脑血管病康复治疗。',
    description:
      '成都中医药大学心血管专业硕士研究生。擅长采用中西医结合的办法治疗各类心血管疾病，包括冠心病、急慢性心衰、各类复杂心律失常、高血压病、风心病、心肌病、心肌炎等多种心血管疾病。从事心血管介入工作多年，累计完成各类心血管介入手术3000余例，包括冠脉造影术，支架植入术，各类起搏器植入术，射频消融术、左心耳封堵术等；致力于心律失常的“绿色电生理”手术，让更多心律失常患者接受手术时免于X射线的危害；熟练运用床旁彩超检测诊断各种心血管疾病。在国内各类心血管核心杂志发表学术论文数篇。目前为四川省中医药学会介入心脏病学专委会秘书；中国中药协会心血管药物研究专委会委员。四川省医促协会高血压分会委员。',
    deptName: '房颤门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/5/4/3/e/62b034ba3bda0.jpg',
    createTs: '2023-03-08 06:23:58',
    updataTs: '2024-05-01 19:56:19',
    districtId: '63',
    deptHisId: '1f5c12b84c59df6f6a16626336eea79a||ZB',
    profession: '医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '79659755',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1559&deptHisId=1f5c12b84c59df6f6a16626336eea79a||ZB&districtCode=2&regType=3',
  },
];

// 心衰
const list4 = [
  {
    doctorId: '2019395',
    docHisId: '1552',
    docName: '谢文',
    level: ' ',
    beGoodAt:
      '运用中西医结合方法诊断治疗高血压、冠心病、急慢性心衰、各种复杂的心律失常、心肌炎、心肌病、先天性心脏病、心脏瓣膜病、心血管疑难疾病等，有深厚的医学理论、丰富和独到的临床经验，擅长心血管疾病冠脉介入、射频消融术、起搏器植入术、TAVR等。在预防心脏疾病、双心医学、心脏康复、中医适宜技术方面有深厚的',
    description:
      '教授、主任医师、硕士研究生导师，四川省名中医，四川省中医心血管专业质控中心业务主任，四川省中医药管理局学术和技术带头人，成都中医药大学附属医院心血管学科带头人，成都中医药大学附属医院胸痛中心、心衰中心业务总监，成都中医药大学附属医院心血管二科科主任，国家中医心血管病临床研究中心四川省中医院分中心主任，奥地利开普勒大学心脏中心访问学者，四川省中医系统心血管专科联盟牵头人，四川省中医药学会心衰(心力衰竭)专委会主任委员，四川省重大疾病心衰病中医药防治中心负责人，四川省中西医结合学会心血管专委会副主任委员，中国中医药学会基层高血压专家指导委员会专家，四川省心脑血管病防治专项行动专家组副组长，四川省老龄健康发展中心中医组副组长',
    deptName: '心衰门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/f/c/a/3/62a28ae2ccb3e.jpg',
    createTs: '2023-03-09 06:23:25',
    updataTs: '2024-04-25 11:58:50',
    districtId: '63',
    deptHisId: '6a10c5b5040a6a99d3af2c885139c9bf||ZB',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '63138898',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1552&deptHisId=6a10c5b5040a6a99d3af2c885139c9bf||ZB&districtCode=2&regType=3',
  },
  {
    doctorId: '2027255',
    docHisId: '1550',
    docName: '胡蓉',
    level: ' ',
    beGoodAt: null,
    description: null,
    deptName: '心衰门诊',
    deptSecondary: '',
    doctorHeadImg: null,
    createTs: '2023-12-26 06:25:47',
    updataTs: '2024-05-01 19:55:58',
    districtId: '63',
    deptHisId: '6a10c5b5040a6a99d3af2c885139c9bf||ZB',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '60865447',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1550&deptHisId=6a10c5b5040a6a99d3af2c885139c9bf||ZB&districtCode=2&regType=3',
  },
  {
    doctorId: '2019394',
    docHisId: '1551',
    docName: '姜莉',
    level: ' ',
    beGoodAt:
      '通过辩证论治治疗风眩、胸痹、心悸、失眠、盗汗、水肿等病症，擅长病种：高血压病、冠心病、心律失常、瓣膜性心脏病、心肌病、慢性心衰、心脏神经症、盗汗、水肿。掌握心血管微创介入手术（冠脉造影术、冠脉内支架植入术、射频消融术、心脏起搏器植入术）的理论知识和操作。',
    description:
      '副主任医师，毕业于重庆医科大学临床医学系。2003年在成都中医药大学附属医院从事临床心血管内科工作至今，并承担心血管科研究生、本科生教学工作。具有较强的临床工作能力，较全面、系统的了解及掌握心血管专业的西医及中医基础理论和专业知识，熟练掌握心血管科临床技术理论和相关前沿理论知识，参与多项国家级、厅局级、校级、院级课题，在国家核心期刊发表论文数十篇，sci两篇，主编专著2部。现任中国心脏联盟心血管疾病预防与康复专业委员会四川联盟常委、四川省中医药学会心衰专委会常委、成都医学会心血管专科分会青年委员会委员、四川省老年医学会介入专委会委员、金牛区“首席家庭医生”。2015年被四川省卫生计生委选派参加援非洲安哥拉医疗队，在安哥拉共和国执行为期两年半的援助任务。<br />',
    deptName: '心衰门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/7/6/5/e/60b9eabe89483.jpg',
    createTs: '2023-03-09 06:23:25',
    updataTs: '2023-12-28 11:58:49',
    districtId: '63',
    deptHisId: '6a10c5b5040a6a99d3af2c885139c9bf||ZB',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '16765854',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1551&deptHisId=6a10c5b5040a6a99d3af2c885139c9bf||ZB&districtCode=2&regType=3',
  },
  {
    doctorId: '2026149',
    docHisId: '1540',
    docName: '王琳',
    level: ' ',
    beGoodAt: null,
    description: null,
    deptName: '心衰门诊',
    deptSecondary: '',
    doctorHeadImg: null,
    createTs: '2023-11-24 06:25:41',
    updataTs: '2024-04-26 11:55:42',
    districtId: '63',
    deptHisId: '6a10c5b5040a6a99d3af2c885139c9bf||ZB',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '47604661',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1540&deptHisId=6a10c5b5040a6a99d3af2c885139c9bf||ZB&districtCode=2&regType=3',
  },
  {
    doctorId: '2027445',
    docHisId: '1543',
    docName: '刘蕾',
    level: ' ',
    beGoodAt: null,
    description: null,
    deptName: '心衰门诊',
    deptSecondary: '',
    doctorHeadImg: null,
    createTs: '2024-01-01 06:26:50',
    updataTs: '2024-05-01 19:56:02',
    districtId: '63',
    deptHisId: '6a10c5b5040a6a99d3af2c885139c9bf||ZB',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '57324004',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1543&deptHisId=6a10c5b5040a6a99d3af2c885139c9bf||ZB&districtCode=2&regType=3',
  },
  {
    doctorId: '2019148',
    docHisId: '1547',
    docName: '赵珏',
    level: ' ',
    beGoodAt: '冠心病，心力衰竭，心律失常，高血压病，失眠、头痛、眩晕，心血管介入诊治技术。',
    description:
      '医师，硕士研究生，毕业于成都中医药大学。从事临床工作多年。擅长中医辨证治疗胸痛、心悸、失眠、头痛、眩晕等病症，同时从事心血管介入诊疗工作，包括冠心病介入以及起搏器植入手术等介入心脏病学诊疗技术，累计完成各类心血管介入手术数千例（包括急性心肌梗死介入诊疗，复杂冠脉病变介入诊疗，防猝死起搏器植入技术等）；参与多项国家级、厅局级、校级课题。',
    deptName: '心衰门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/7/f/6/c/607eb4c6d0002.jpg',
    createTs: '2023-03-07 06:27:33',
    updataTs: '2023-08-29 11:58:40',
    districtId: '63',
    deptHisId: '6a10c5b5040a6a99d3af2c885139c9bf||ZB',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '66828294',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1547&deptHisId=6a10c5b5040a6a99d3af2c885139c9bf||ZB&districtCode=2&regType=3',
  },
];

const list5 = [
  {
    doctorId: '2025039',
    docHisId: '1541',
    docName: '王卫星',
    level: ' ',
    beGoodAt:
      '心力衰竭、冠心病、心肌缺血、高血压病、心律失常、瓣膜性心脏病、心肌病、心脏神经症、心血管介入技术；头痛、眩晕、胸闷、胸痛、心悸、气短、中风、失眠、多梦、等多种心脑血管疾病。',
    description:
      '1982年毕业于成都中医药大学（原成都中医学院）医疗系。现任成都中医药大学附属医院心血管二科负责人，大内科副主任，主任医师，硕士生导师，四川省名中医，目前担任中国医师协会中西医结合分会高血压专家委员会委员、环球中医药杂志编委、四川省中医药学会中医内科老年病专委会委员、四川省中医药学会心脑血管病专委会委员、四川省中西医结合学会心血管病专委会委员、成都市医学会心血管专委会委员、成都市医学会循证医学专委会委员。从事临床及教学30余年。主持国家级科研课题3项；省级科研课题4项；厅级课题2项。参加国家级及省部级课题4项。在国内医学专业杂志发表论文40余篇。',
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/c/4/e/9/65c41db0e5703.jpg',
    createTs: '2023-09-30 06:27:10',
    updataTs: '2024-04-27 16:59:36',
    districtId: '63',
    deptHisId: '46||TX',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '19694495',
    doc_code: null,
    tooltips: '',
    profession_img: null,
    political_face: '',
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1541&deptHisId=46||TX&districtCode=2&regType=3',
  },
  {
    doctorId: '2030073',
    docHisId: '1542',
    docName: '杨思进',
    level: ' ',
    beGoodAt: null,
    description: null,
    deptName: '心血管二科门诊',
    deptSecondary: '',
    doctorHeadImg: null,
    createTs: '2024-04-25 10:17:27',
    updataTs: '2024-04-28 00:03:09',
    districtId: '63',
    deptHisId: '46||TX',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '65726214',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1542&deptHisId=46||TX&districtCode=2&regType=3',
  },
  {
    doctorId: '2018537',
    docHisId: '1553',
    docName: '陈光宇',
    level: ' ',
    beGoodAt:
      '高血压病、高心病、冠心病、心肌炎、心肌病、心力衰竭、心律失常、高脂血症、心血管神经症、失眠、头痛等疾病的治疗。',
    description:
      '<p> <b>四川省名中医，</b><b>主任医师，</b><b>四川省中医药学会心脑血管病专委会委员</b><b>，</b><b>四川省中西医结合学会心血管病专委会委员，四川省中医药介入心脏病学</b><b>会</b><b>专委会委员，本硕连读七年制硕士研究生导师。1984年</b><b>毕业于成都中医药大学</b><b>(</b><b>原成都中医学院）医学系，学士学位，</b><b>毕业后长期在本院从事临床医疗、教学和科研工作。先后发表论文十多篇，负责及参加部省级和厅局级科研课题多项。</b><b>从医</b><b>30</b><b>多年来，</b><b>对中医胸痹心痛，</b><b>风眩，</b><b>心瘅，心痹，心衰，心悸，不寐，头痛等疾病的辨证施治有丰富的临床经验和独到之处。</b> </p> <p> <b></b> </p>',
    deptName: '心血管一科门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/7/d/0/c/5ed5c36bd5c54.jpg',
    createTs: '2023-03-03 06:27:26',
    updataTs: '2024-05-01 20:01:36',
    districtId: '63',
    deptHisId: '45||TX',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '84729531',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1553&deptHisId=45||TX&districtCode=2&regType=3',
  },
  {
    doctorId: '2018527',
    docHisId: '1552',
    docName: '谢文',
    level: ' ',
    beGoodAt:
      '运用中西医结合方法诊断治疗高血压、冠心病、急慢性心衰、各种复杂的心律失常、心肌炎、心肌病、先天性心脏病、心脏瓣膜病、心血管疑难疾病等，有深厚的医学理论、丰富和独到的临床经验，擅长心血管疾病冠脉介入、射频消融术、起搏器植入术、TAVR等。在预防心脏疾病、双心医学、心脏康复、中医适宜技术方面有深厚的',
    description:
      '教授、主任医师、硕士研究生导师，四川省名中医，四川省中医心血管专业质控中心业务主任，四川省中医药管理局学术和技术带头人，成都中医药大学附属医院心血管学科带头人，成都中医药大学附属医院胸痛中心、心衰中心业务总监，成都中医药大学附属医院心血管二科科主任，国家中医心血管病临床研究中心四川省中医院分中心主任，奥地利开普勒大学心脏中心访问学者，四川省中医系统心血管专科联盟牵头人，四川省中医药学会心衰(心力衰竭)专委会主任委员，四川省重大疾病心衰病中医药防治中心负责人，四川省中西医结合学会心血管专委会副主任委员，中国中医药学会基层高血压专家指导委员会专家，四川省心脑血管病防治专项行动专家组副组长，四川省老龄健康发展中心中医组副组长',
    deptName: '心律失常门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/7/4/a/a/62a28afae51c2.jpg',
    createTs: '2023-03-03 06:27:19',
    updataTs: '2024-05-01 20:01:20',
    districtId: '63',
    deptHisId: 'd7248ff3fc62bda592dbcceb30fdbaf5||ZB',
    profession: '主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '63138898',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1552&deptHisId=d7248ff3fc62bda592dbcceb30fdbaf5||ZB&districtCode=2&regType=3',
  },
  {
    doctorId: '2019268',
    docHisId: '1550',
    docName: '胡蓉',
    level: ' ',
    beGoodAt:
      '对高血压病、高血压心脏病、急慢性心力衰竭、冠心病、不稳定型心绞痛、心肌梗死，冠脉支架植入术后心绞痛、微血管型心绞痛、心律失常（房颤、早搏）、瓣膜性心脏病（风湿性心脏病）、心肌炎、心肌病、心脏神经症，胃心综合征、胆心综合征等心血管疾病的诊治及共病管理，对中医病症如心悸、胸痹心痛、头痛、中风、水肿、失眠',
    description:
      '2005年毕业于成都中医药大学中西医结合临床专业，获硕士学位。师从原中医附院大内科主任戴万亨教授、四川省人民医院心血管内科专家姜荣建主任医师。从事中西医结合临床、教学、科研10余年，参与多项国家级、厅局级、院级课题，在国家级核心期刊发表论文数篇，参编专著2部。',
    deptName: '心律失常门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/3/8/b/a/62b13793b5fd0.jpg',
    createTs: '2023-03-08 06:24:36',
    updataTs: '2024-05-01 20:01:14',
    districtId: '63',
    deptHisId: 'd7248ff3fc62bda592dbcceb30fdbaf5||ZB',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '60865447',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1550&deptHisId=d7248ff3fc62bda592dbcceb30fdbaf5||ZB&districtCode=2&regType=3',
  },
  {
    doctorId: '2026102',
    docHisId: '1540',
    docName: '王琳',
    level: ' ',
    beGoodAt: null,
    description: null,
    deptName: '心律失常门诊',
    deptSecondary: '',
    doctorHeadImg: null,
    createTs: '2023-11-22 06:25:08',
    updataTs: '2023-12-13 17:29:03',
    districtId: '63',
    deptHisId: 'd7248ff3fc62bda592dbcceb30fdbaf5||ZB',
    profession: '副主任医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '47604661',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1540&deptHisId=d7248ff3fc62bda592dbcceb30fdbaf5||ZB&districtCode=2&regType=3',
  },
  {
    doctorId: '2019267',
    docHisId: '1543',
    docName: '刘蕾',
    level: ' ',
    beGoodAt:
      '冠心病，高血压病 高血压心脏病，风湿性心脏病，急慢性心力衰竭，心律失常等多种心血管疾病的中西医结合诊治。以及心脏神经功能紊乱引起的各种症状的治疗。',
    description:
      '毕业于成都中医药大学中西结合硕士专业，从事中西医结合临床工作多年，师从四川省十大名中医刘永家教授，擅长通过中医辨证论治改善胸痛、心衰、心律失常、高血压、冠心病等心血管疾病症状及预后，擅长中西医结合治疗心悸、头痛、眩晕等症。心衰中心委员，老年病协会委员，参与研究国家自然科学基金课题，多项国家级、厅局级、校级课题，发表包括SCI 核心期刊等多篇论文。',
    deptName: '心律失常门诊',
    deptSecondary: '',
    doctorHeadImg: '/uploads/y/MbTXcN1k/b/4/4/f/6109e43367f45.jpg',
    createTs: '2023-03-08 06:24:36',
    updataTs: '2024-05-01 20:01:14',
    districtId: '63',
    deptHisId: 'd7248ff3fc62bda592dbcceb30fdbaf5||ZB',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '57324004',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1543&deptHisId=d7248ff3fc62bda592dbcceb30fdbaf5||ZB&districtCode=2&regType=3',
  },
  {
    doctorId: '2027306',
    docHisId: '1720',
    docName: '唐秀容',
    level: ' ',
    beGoodAt: null,
    description: null,
    deptName: '心律失常门诊',
    deptSecondary: '',
    doctorHeadImg: null,
    createTs: '2023-12-28 06:24:16',
    updataTs: '2024-04-25 17:22:06',
    districtId: '63',
    deptHisId: 'd7248ff3fc62bda592dbcceb30fdbaf5||ZB',
    profession: '主治医师',
    isShow: '1',
    isDelete: '0',
    hospitalId: '176',
    waitUpdate: '0',
    sort: '0',
    isProfession: '0',
    maxRegNum: null,
    regStatus: '1',
    emt_doctor_id: '91205017',
    doc_code: null,
    tooltips: null,
    profession_img: null,
    political_face: null,
    linkUrl:
      '/index.php?g=Weixin&m=CloudRegisterThree&a=four&wx=MbTXcN1k&docHisId=1720&deptHisId=d7248ff3fc62bda592dbcceb30fdbaf5||ZB&districtCode=2&regType=3',
  },
];

const map: Record<string, boolean> = {};
const source = [...ke1, ...ke2, ...list3, ...list4, ...list5].filter(item => {
  if (map[item.docName]) {
    return false;
  }
  map[item.docName] = true;
  return true;
});

const KeywordReg = /(反流|狭窄|主动脉瓣|二尖瓣|三尖瓣|房颤|心房纤颤|过速|衰竭|心律失常|弱|瓣膜)/;

export default function () {
  const [keyword1, setKeyword1] = useState('/(反流|狭窄|主动脉瓣|二尖瓣|三尖瓣|房颤|心房纤颤|过速|衰竭|心律失常|弱|瓣膜)/g');
  const [keyword2, setKeyword2] = useState('');
  const [filterKeyword, setCheck] = useState(false);

  const list = useMemo(() => {
    let ls = source;
    if (filterKeyword) {
      ls = ls.filter(item => KeywordReg.test(item?.beGoodAt ?? ''));
    }
    try {
      if (keyword1) {
        ls = ls.filter(item => createRegExp(keyword1)[0].test(item?.beGoodAt ?? ''));
      }
      if (keyword2) {
        ls = ls.filter(item => createRegExp(keyword2)[0].test(item?.beGoodAt ?? ''));
      }
    } catch (_) {}

    return ls;
  }, [filterKeyword, keyword1, keyword2]);

  const columns = [
    {
      title: '姓名',
      key: 'docName',
      render: (_: unknown, record: any, index: number) => (
        <span style={{whiteSpace: 'nowrap'}}>
          {index + 1}. {record.docName}
        </span>
      ),
    },
    {
      title: '职称',
      render: (_: unknown, record: any) => <span style={{whiteSpace: 'nowrap'}}>{record.profession || '-'}</span>,
    },
    {
      title: '擅长',
      dataIndex: 'beGoodAt',
      width: '50%',
      render(_: unknown, record: any) {
        const result = traverse(record.beGoodAt, KeywordReg, {
          mode: 'string',
          style: 'color:red; font-size: larger; font-weight: bold;',
        });
        if (result) {
          return <p dangerouslySetInnerHTML={{__html: result.container as 'string'}}></p>;
        }
        return record.beGoodAt;
      },
    },
    {
      title: '简介',
      dataIndex: 'description',
      render(_: unknown, record: any) {
        const result = traverse(record.description, KeywordReg, {
          mode: 'string',
          style: 'color:red; font-size: larger; font-weight: bold;',
        });
        if (result) {
          return <p dangerouslySetInnerHTML={{__html: result.container as 'string'}}></p>;
        }
        return record.description;
      },
    },
    {
      title: '科室',
      render: (_: unknown, record: any) => <span style={{whiteSpace: 'nowrap'}}>{record.deptName}</span>,
    },
  ];

  return (
    <div style={{padding: '20px'}}>
      <label>
        keyword1:
        <input value={keyword1} onInput={(e: any) => setKeyword1(e.target.value)} />
      </label>
      <label>
        keyword2:
        <input value={keyword2} onInput={(e: any) => setKeyword2(e.target.value)} />
      </label>
      <Checkbox
        checked={filterKeyword}
        onChange={e => {
          setCheck(e.target.checked);
        }}>
        过滤关键词
      </Checkbox>

      <div>总共 {list.length} 条</div>
      <Table rowKey={'docName'} dataSource={list} columns={columns} pagination={false} />
    </div>
  );
}
